package hobby

import (
	"net/http"
	"strings"

	"github.com/kumargaurav/summit-backend/internal/httpx"
)

// DiscoverCard is one entry in the Ascent "Discover" feed — a trackable SKILL or a
// FACT worth knowing. JSON tags mirror the Kotlin client's DiscoverCardDto.
type DiscoverCard struct {
	ID       string   `json:"id"`
	HobbyID  string   `json:"hobbyId"`
	Kind     string   `json:"kind"`
	Title    string   `json:"title"`
	Tagline  string   `json:"tagline"`
	Body     string   `json:"body"`
	ImageURL string   `json:"imageUrl"`
	Meta     []string `json:"meta"`
}

// Discover returns the curated cards for the requested hobby ids (?ids=a,b,c),
// preserving per-hobby order; the client interleaves for variety.
func (h *Handler) Discover(w http.ResponseWriter, r *http.Request) {
	want := map[string]bool{}
	for _, id := range strings.Split(r.URL.Query().Get("ids"), ",") {
		if s := strings.TrimSpace(id); s != "" {
			want[s] = true
		}
	}
	out := []DiscoverCard{}
	for _, c := range discoverCards {
		if len(want) == 0 || want[c.HobbyID] {
			out = append(out, c)
		}
	}
	httpx.JSON(w, http.StatusOK, map[string]any{"cards": out})
}

var discoverCards = []DiscoverCard{
	{ID: "sk_fitness_deadlift", HobbyID: "fitness", Kind: "SKILL", Title: "Deadlift", Tagline: "The one lift that trains your whole back side.", Body: "The deadlift works your glutes, hamstrings, back and grip in one movement — the closest thing to a strength cheat code. Start light, keep the bar close, push the floor away. Track it and watch the number climb week over week.", ImageURL: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?auto=format&fit=crop&w=400&q=80", Meta: []string{"Full-body", "3×5 reps", "Start light"}},
	{ID: "sk_fitness_squat", HobbyID: "fitness", Kind: "SKILL", Title: "Back squat", Tagline: "The king of lower-body strength.", Body: "Squats build legs, core and bone density. Depth over weight: master bodyweight first, then goblet, then barbell. Adding 2.5 kg a week compounds into a doubled squat within a year.", ImageURL: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?auto=format&fit=crop&w=400&q=80", Meta: []string{"Legs + core", "3×8 reps"}},
	{ID: "sk_fitness_plank", HobbyID: "fitness", Kind: "SKILL", Title: "Plank progressions", Tagline: "Core strength you'll feel in every other lift.", Body: "From forearm plank to side plank to weighted — a strong midline makes your squat, deadlift and posture better. 3 rounds of 45 seconds, most days.", ImageURL: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?auto=format&fit=crop&w=400&q=80", Meta: []string{"Core", "45s holds"}},
	{ID: "fc_fitness_recovery", HobbyID: "fitness", Kind: "FACT", Title: "Muscle grows on rest days", Tagline: "Training is the stimulus, sleep is the builder.", Body: "Muscle protein synthesis peaks in the 24–48h after a session — mostly while you sleep. Under 7 hours of sleep can cut strength gains measurably. Logging rest days is logging progress.", ImageURL: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?auto=format&fit=crop&w=400&q=80", Meta: []string{}},
	{ID: "sk_running_intervals", HobbyID: "running", Kind: "SKILL", Title: "Interval runs", Tagline: "Short bursts that raise your ceiling.", Body: "6–8 rounds of 1 minute fast / 2 minutes easy. Intervals push your VO₂max — the engine size for every distance. One session a week is enough; the rest stays easy.", ImageURL: "https://images.unsplash.com/photo-1476480862126-209bfaa8edc8?auto=format&fit=crop&w=400&q=80", Meta: []string{"Speed", "1 min on / 2 off"}},
	{ID: "sk_running_tempo", HobbyID: "running", Kind: "SKILL", Title: "Tempo runs", Tagline: "Comfortably hard — the pace that moves your threshold.", Body: "20 minutes at a pace where talking is possible but unpleasant. Tempo runs teach your body to clear lactate faster, which is what makes race pace feel easier.", ImageURL: "https://images.unsplash.com/photo-1476480862126-209bfaa8edc8?auto=format&fit=crop&w=400&q=80", Meta: []string{"Endurance", "20 min steady"}},
	{ID: "sk_running_long", HobbyID: "running", Kind: "SKILL", Title: "The long run", Tagline: "Slow, far, and the most important run of the week.", Body: "Once a week, run longer than usual at a conversational pace. It builds capillaries, fat metabolism and mental durability. Add ten percent at a time.", ImageURL: "https://images.unsplash.com/photo-1476480862126-209bfaa8edc8?auto=format&fit=crop&w=400&q=80", Meta: []string{"Base", "+10%/week"}},
	{ID: "fc_running_cadence", HobbyID: "running", Kind: "FACT", Title: "Cadence beats stride length", Tagline: "Quicker, shorter steps protect your knees.", Body: "Elite runners average ~170–180 steps a minute. Overstriding sends braking force through your joints; a faster cadence keeps your feet under your body. Count your steps for 30 seconds on your next run.", ImageURL: "https://images.unsplash.com/photo-1476480862126-209bfaa8edc8?auto=format&fit=crop&w=400&q=80", Meta: []string{}},
	{ID: "sk_music_barre", HobbyID: "music", Kind: "SKILL", Title: "Barre chords", Tagline: "One shape unlocks the whole fretboard.", Body: "The F-major barre is the wall most guitarists hit — and the door. Once your index finger can press all six strings, every major and minor chord becomes one movable shape. Five minutes daily beats an hour weekly.", ImageURL: "https://images.unsplash.com/photo-1510915361894-db8b60106cb1?auto=format&fit=crop&w=400&q=80", Meta: []string{"Guitar", "5 min/day"}},
	{ID: "sk_music_fingerpicking", HobbyID: "music", Kind: "SKILL", Title: "Fingerpicking", Tagline: "Turn chords into music.", Body: "Travis picking — thumb keeps the bass, fingers sing the melody. Start with the C chord: thumb-index-middle-index. Slow is smooth, smooth is fast.", ImageURL: "https://images.unsplash.com/photo-1510915361894-db8b60106cb1?auto=format&fit=crop&w=400&q=80", Meta: []string{"Guitar", "Pattern practice"}},
	{ID: "sk_music_ear", HobbyID: "music", Kind: "SKILL", Title: "Ear training", Tagline: "Play what you hear, not just what you read.", Body: "Interval recognition is a superpower: start with just two — the octave and the fifth. Ten minutes with an ear-training app and within a month you'll pick melodies out of thin air.", ImageURL: "https://images.unsplash.com/photo-1510915361894-db8b60106cb1?auto=format&fit=crop&w=400&q=80", Meta: []string{"Any instrument", "10 min/day"}},
	{ID: "fc_music_guitar_fact", HobbyID: "music", Kind: "FACT", Title: "Your brain on ten minutes of practice", Tagline: "Playing lights up more brain regions than almost any activity.", Body: "Neuroscientists call playing an instrument a full-brain workout — motor, auditory and visual cortices firing together. Ten focused minutes a day measurably grows neural pathways within weeks.", ImageURL: "https://images.unsplash.com/photo-1510915361894-db8b60106cb1?auto=format&fit=crop&w=400&q=80", Meta: []string{}},
	{ID: "sk_dance_eightcount", HobbyID: "dance", Kind: "SKILL", Title: "The 8-count", Tagline: "Every routine is built from this one unit.", Body: "Music for dance is counted in eights. Train yourself to hear it: play any song and count 1-through-8 on the beat. Once you feel the eight, choreography stops being memorisation and starts being music.", ImageURL: "https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?auto=format&fit=crop&w=400&q=80", Meta: []string{"Foundation", "Any style"}},
	{ID: "sk_dance_grooves", HobbyID: "dance", Kind: "SKILL", Title: "Basic grooves", Tagline: "Bounce and rock — the two moves under everything.", Body: "Before moves comes groove: the bounce (down on the beat) and the rock (side to side). Drill them in a mirror until they live in your body. Every style from hip-hop to salsa sits on top.", ImageURL: "https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?auto=format&fit=crop&w=400&q=80", Meta: []string{"Hip-hop", "Mirror practice"}},
	{ID: "fc_dance_social", HobbyID: "dance", Kind: "FACT", Title: "Dance is the stickiest exercise", Tagline: "People quit gyms; they rarely quit dance.", Body: "Studies on exercise adherence consistently rank partnered and social dance top — the music, community and skill curve keep people coming back for years, not weeks.", ImageURL: "https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?auto=format&fit=crop&w=400&q=80", Meta: []string{}},
	{ID: "sk_reading_notes", HobbyID: "reading", Kind: "SKILL", Title: "Reading with notes", Tagline: "Turn what you read into what you keep.", Body: "One line per chapter, in your own words. The act of translating a chapter into a sentence is where comprehension happens. Log each book's best three ideas when you finish.", ImageURL: "https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=400&q=80", Meta: []string{"Retention", "1 line/chapter"}},
	{ID: "sk_reading_habit", HobbyID: "reading", Kind: "SKILL", Title: "The 20-page rule", Tagline: "Twenty pages a day is 30 books a year.", Body: "Momentum beats motivation. Twenty pages takes ~25 minutes — one commute, one lunch break. Track your daily twenty and the yearly number takes care of itself.", ImageURL: "https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=400&q=80", Meta: []string{"Habit", "20 pages/day"}},
	{ID: "fc_reading_fiction", HobbyID: "reading", Kind: "FACT", Title: "Fiction builds empathy", Tagline: "Novels are a gym for theory of mind.", Body: "Research shows literary fiction readers score higher on tests of empathy and social reasoning — living inside other minds for hundreds of pages is practice for real ones.", ImageURL: "https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=400&q=80", Meta: []string{}},
	{ID: "sk_trekking_pacing", HobbyID: "trekking", Kind: "SKILL", Title: "Mountain pacing", Tagline: "Slow enough to talk, steady enough to summit.", Body: "The alpine rule: a pace you can hold a conversation at, with rest steps on steep ground. Most people blow up in the first hour. The mountain rewards the tortoise.", ImageURL: "https://images.unsplash.com/photo-1551632811-561732d1e306?auto=format&fit=crop&w=400&q=80", Meta: []string{"Endurance", "Rest-step"}},
	{ID: "sk_trekking_packing", HobbyID: "trekking", Kind: "SKILL", Title: "Pack discipline", Tagline: "Every gram you carry, you carry uphill.", Body: "Base weight under 8 kg changes everything. Lay everything out, then remove a third. Water, layers, light, first-aid — the four things you never cut.", ImageURL: "https://images.unsplash.com/photo-1551632811-561732d1e306?auto=format&fit=crop&w=400&q=80", Meta: []string{"Preparation", "<8 kg base"}},
	{ID: "fc_trekking_altitude", HobbyID: "trekking", Kind: "FACT", Title: "Altitude rewires your blood", Tagline: "Two weeks high doubles your oxygen efficiency.", Body: "Above 2,500 m your body starts producing more red blood cells within days — the same adaptation elite athletes chase with altitude camps. Acclimatise slowly: climb high, sleep low.", ImageURL: "https://images.unsplash.com/photo-1551632811-561732d1e306?auto=format&fit=crop&w=400&q=80", Meta: []string{}},
	{ID: "sk_art_value", HobbyID: "art", Kind: "SKILL", Title: "Value studies", Tagline: "Get light right and colour follows.", Body: "Paint or sketch in only three tones — dark, mid, light. Value structure is why a black-and-white photo of a great painting still works. Ten small studies teach more than one big piece.", ImageURL: "https://images.unsplash.com/photo-1513364776144-60967b0f800f?auto=format&fit=crop&w=400&q=80", Meta: []string{"Foundation", "3 tones"}},
	{ID: "sk_art_gesture", HobbyID: "art", Kind: "SKILL", Title: "Gesture drawing", Tagline: "Capture the energy in 60 seconds.", Body: "One-minute figure sketches force you to see the whole before the details. Twenty gestures a day for a month will change your drawing more than anything else.", ImageURL: "https://images.unsplash.com/photo-1513364776144-60967b0f800f?auto=format&fit=crop&w=400&q=80", Meta: []string{"Figure", "60s sketches"}},
	{ID: "fc_art_flow", HobbyID: "art", Kind: "FACT", Title: "Art is a proven stress valve", Tagline: "45 minutes of making lowers cortisol.", Body: "A Drexel study found 45 minutes of art-making significantly reduced cortisol in 75% of participants — regardless of skill level. The benefit is in the making, not the masterpiece.", ImageURL: "https://images.unsplash.com/photo-1513364776144-60967b0f800f?auto=format&fit=crop&w=400&q=80", Meta: []string{}},
	{ID: "sk_photography_triangle", HobbyID: "photography", Kind: "SKILL", Title: "The exposure triangle", Tagline: "Aperture, shutter, ISO — the whole craft in three dials.", Body: "Every photo is a trade between depth (aperture), motion (shutter) and noise (ISO). Shoot the same scene at three apertures and the triangle stops being theory.", ImageURL: "https://images.unsplash.com/photo-1502920917128-1aa500764cbd?auto=format&fit=crop&w=400&q=80", Meta: []string{"Foundation", "Manual mode"}},
	{ID: "sk_photography_golden", HobbyID: "photography", Kind: "SKILL", Title: "Golden hour discipline", Tagline: "The hour that makes amateurs look professional.", Body: "Low sun means soft shadows, warm tones, and drama in every direction. Plan one shoot this week for the hour after sunrise or before sunset — same place you'd normally shoot at noon.", ImageURL: "https://images.unsplash.com/photo-1502920917128-1aa500764cbd?auto=format&fit=crop&w=400&q=80", Meta: []string{"Light", "1 hr window"}},
	{ID: "fc_photography_composition", HobbyID: "photography", Kind: "FACT", Title: "Your eye already knows the rule of thirds", Tagline: "Renaissance painters used it before cameras existed.", Body: "Off-centre subjects feel alive because human vision scans in thirds. Turn on your camera's grid and place eyes — human or animal — on the top-third line.", ImageURL: "https://images.unsplash.com/photo-1502920917128-1aa500764cbd?auto=format&fit=crop&w=400&q=80", Meta: []string{}},
	{ID: "sk_football_firsttouch", HobbyID: "football", Kind: "SKILL", Title: "First touch", Tagline: "The skill that buys you time.", Body: "Wall work: fifty touches per foot, cushioning the ball dead each time. A clean first touch is the difference between playing and chasing. Ten minutes daily.", ImageURL: "https://images.unsplash.com/photo-1517927033932-b3d18e61fb3a?auto=format&fit=crop&w=400&q=80", Meta: []string{"Control", "50 touches/foot"}},
	{ID: "sk_football_weakfoot", HobbyID: "football", Kind: "SKILL", Title: "Weak foot training", Tagline: "Two-footed players get picked first.", Body: "One session a week using only your weak foot — passing, shooting, first touch. It feels terrible for two weeks and then it doesn't. Defenders can't show you anywhere.", ImageURL: "https://images.unsplash.com/photo-1517927033932-b3d18e61fb3a?auto=format&fit=crop&w=400&q=80", Meta: []string{"Technique", "1 session/week"}},
	{ID: "fc_football_scanning", HobbyID: "football", Kind: "FACT", Title: "Elite players look away from the ball", Tagline: "Top midfielders scan 8 times per 10 seconds.", Body: "Research on elite midfielders found they check their shoulders up to eight times in the ten seconds before receiving. Scanning before the ball arrives is why they always seem to have time.", ImageURL: "https://images.unsplash.com/photo-1517927033932-b3d18e61fb3a?auto=format&fit=crop&w=400&q=80", Meta: []string{}},
	{ID: "sk_adventure_climbing", HobbyID: "adventure", Kind: "SKILL", Title: "Climbing grades", Tagline: "Your first 6a is closer than you think.", Body: "Indoor bouldering meets you at your level — V0 needs no experience. Grip strength arrives fast; technique (silent feet, straight arms) is what actually gets you up the wall.", ImageURL: "https://images.unsplash.com/photo-1522163182402-834f871fd851?auto=format&fit=crop&w=400&q=80", Meta: []string{"Climbing", "V0 start"}},
	{ID: "sk_adventure_breath", HobbyID: "adventure", Kind: "SKILL", Title: "Breath control", Tagline: "The skill under every adventure sport.", Body: "Box breathing — 4 in, 4 hold, 4 out, 4 hold — steadies your nervous system before a rapid, a jump, or a crux move. Panic wastes oxygen; calm is a trainable skill.", ImageURL: "https://images.unsplash.com/photo-1522163182402-834f871fd851?auto=format&fit=crop&w=400&q=80", Meta: []string{"Mental", "4-4-4-4"}},
	{ID: "fc_adventure_fear", HobbyID: "adventure", Kind: "FACT", Title: "Fear and excitement are the same chemical", Tagline: "The label is a choice your brain makes.", Body: "Adrenaline is identical in dread and thrill — studies show reframing 'I'm scared' as 'I'm excited' measurably improves performance. Adventure sports are literally practice at choosing the label.", ImageURL: "https://images.unsplash.com/photo-1522163182402-834f871fd851?auto=format&fit=crop&w=400&q=80", Meta: []string{}},
	{ID: "sk_gaming_aim", HobbyID: "gaming", Kind: "SKILL", Title: "Deliberate aim training", Tagline: "Ten warm-up minutes that carry your whole session.", Body: "Raw hours don't improve aim — deliberate practice does. Ten minutes of tracking and flick drills before ranked, with a consistent sensitivity, beats three hours of tilted queueing.", ImageURL: "https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=400&q=80", Meta: []string{"FPS", "10 min warm-up"}},
	{ID: "sk_gaming_vod", HobbyID: "gaming", Kind: "SKILL", Title: "Review your own replays", Tagline: "Find the one mistake you make every game.", Body: "Watch one of your own games per week and hunt a single repeated error — not highlights, mistakes. Fixing one habit per week is how ranks actually change.", ImageURL: "https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=400&q=80", Meta: []string{"Improvement", "1 VOD/week"}},
	{ID: "fc_gaming_reaction", HobbyID: "gaming", Kind: "FACT", Title: "Pros aren't faster — they predict", Tagline: "Reaction time matters less than pattern reading.", Body: "Studies of esports pros show average reaction times barely above the general population. Their edge is anticipation: reading patterns early enough that speed stops mattering.", ImageURL: "https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=400&q=80", Meta: []string{}},
	{ID: "sk_writing_morning", HobbyID: "writing", Kind: "SKILL", Title: "Morning pages", Tagline: "Three pages before the critic wakes up.", Body: "Write three longhand pages of anything, first thing. It's a warm-up, a therapist and an idea mine at once. The rule: don't stop, don't edit, don't read them for a month.", ImageURL: "https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=400&q=80", Meta: []string{"Habit", "3 pages/day"}},
	{ID: "fc_writing_clarity", HobbyID: "writing", Kind: "FACT", Title: "Writing is thinking made visible", Tagline: "Confused writing is confused thought.", Body: "As the saying goes: writing is nature's way of letting you know how sloppy your thinking is. One clear paragraph a day compounds into clear thinking everywhere.", ImageURL: "https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=400&q=80", Meta: []string{}},
}
