package hobby

// picks: hand-curated discovery lists per hobby — what to read / try / explore, not where.
// Tap one in the app to add it to "My Ascent" and start logging against it. Hobbies without
// an entry fall back to an empty list (the client then shows only nearby places).
var picks = map[string]Picks{
	"reading": {Title: "Popular books to read", Items: []Pick{
		{Title: "Atomic Habits", Subtitle: "James Clear", Meta: "Self-improvement"},
		{Title: "The Alchemist", Subtitle: "Paulo Coelho", Meta: "Fiction"},
		{Title: "Sapiens", Subtitle: "Yuval Noah Harari", Meta: "History"},
		{Title: "The Psychology of Money", Subtitle: "Morgan Housel", Meta: "Finance"},
		{Title: "Ikigai", Subtitle: "Héctor García", Meta: "Wellbeing"},
		{Title: "Deep Work", Subtitle: "Cal Newport", Meta: "Focus"},
	}},
	"adventure": {Title: "Adventure sports to try", Items: []Pick{
		{Title: "Rock climbing", Meta: "Strength · technique"},
		{Title: "Scuba diving", Meta: "Certification"},
		{Title: "Paragliding", Meta: "Tandem to solo"},
		{Title: "White-water rafting", Meta: "Grade I–V"},
		{Title: "Surfing", Meta: "Coastal"},
		{Title: "Mountain biking", Meta: "Trails"},
		{Title: "Skydiving", Meta: "Tandem jump"},
	}},
	"art": {Title: "Art forms to explore", Items: []Pick{
		{Title: "Sketching & drawing", Meta: "Pencil · ink"},
		{Title: "Watercolour painting", Meta: "Beginner-friendly"},
		{Title: "Acrylic painting", Meta: "Versatile"},
		{Title: "Digital art", Meta: "Tablet"},
		{Title: "Calligraphy", Meta: "Lettering"},
		{Title: "Pottery & ceramics", Meta: "Hands-on"},
		{Title: "Printmaking", Meta: "Lino · screen"},
	}},
	"dance": {Title: "Dance styles", Items: []Pick{
		{Title: "Hip-hop", Meta: "High energy"},
		{Title: "Salsa", Meta: "Partner"},
		{Title: "Bachata", Meta: "Partner"},
		{Title: "Contemporary", Meta: "Expressive"},
		{Title: "Bharatanatyam", Meta: "Classical"},
		{Title: "Kathak", Meta: "Classical"},
	}},
	"music": {Title: "Pick an instrument", Items: []Pick{
		{Title: "Guitar", Meta: "4 chords to start"},
		{Title: "Piano", Meta: "Great for theory"},
		{Title: "Ukulele", Meta: "Easiest start"},
		{Title: "Singing", Meta: "No gear"},
		{Title: "Drums", Meta: "Rhythm"},
		{Title: "Music production", Meta: "DAW"},
	}},
	"running": {Title: "Distances to chase", Items: []Pick{
		{Title: "Parkrun 5K", Meta: "Weekly · free"},
		{Title: "10K", Meta: "Next step"},
		{Title: "Half marathon", Meta: "21.1K"},
		{Title: "Marathon", Meta: "42.2K"},
		{Title: "Trail run", Meta: "Off-road"},
	}},
	"trekking": {Title: "Treks to aim for", Items: []Pick{
		{Title: "Kedarkantha", Subtitle: "Uttarakhand", Meta: "Beginner · winter"},
		{Title: "Hampta Pass", Subtitle: "Himachal", Meta: "Moderate"},
		{Title: "Roopkund", Subtitle: "Uttarakhand", Meta: "Difficult"},
		{Title: "Everest Base Camp", Subtitle: "Nepal", Meta: "High altitude"},
		{Title: "Kilimanjaro", Subtitle: "Tanzania", Meta: "Summit"},
	}},
	"gaming": {Title: "Genres to dive into", Items: []Pick{
		{Title: "FPS", Meta: "Valorant · CS2"},
		{Title: "MOBA", Meta: "Dota · LoL"},
		{Title: "Battle royale", Meta: "Squad up"},
		{Title: "RPG", Meta: "Story-rich"},
		{Title: "Strategy", Meta: "Build orders"},
		{Title: "Cozy / Indie", Meta: "Relax"},
	}},
	"photography": {Title: "Genres to shoot", Items: []Pick{
		{Title: "Street", Meta: "Candid"},
		{Title: "Portrait", Meta: "People"},
		{Title: "Landscape", Meta: "Golden hour"},
		{Title: "Astrophotography", Meta: "Night sky"},
		{Title: "Macro", Meta: "Close-up"},
		{Title: "Wildlife", Meta: "Patience"},
	}},
	"fitness": {Title: "Training styles", Items: []Pick{
		{Title: "Strength training", Meta: "Barbell · dumbbell"},
		{Title: "HIIT", Meta: "Short · intense"},
		{Title: "Calisthenics", Meta: "Bodyweight"},
		{Title: "Yoga", Meta: "Mobility"},
		{Title: "CrossFit", Meta: "Mixed"},
		{Title: "Pilates", Meta: "Core"},
	}},
	"writing": {Title: "Forms to try", Items: []Pick{
		{Title: "Journaling", Meta: "Daily"},
		{Title: "Short stories", Meta: "Fiction"},
		{Title: "Poetry", Meta: "Verse"},
		{Title: "Blogging", Meta: "Online"},
		{Title: "Screenwriting", Meta: "Scripts"},
	}},
	"learning": {Title: "Skills to pick up", Items: []Pick{
		{Title: "A new language", Meta: "Daily practice"},
		{Title: "Coding", Meta: "Build projects"},
		{Title: "Public speaking", Meta: "Confidence"},
		{Title: "Chess", Meta: "Strategy"},
		{Title: "Cooking basics", Meta: "Everyday"},
	}},
	"travel": {Title: "Trip ideas", Items: []Pick{
		{Title: "Mountain getaway", Meta: "Cool climate"},
		{Title: "Beach escape", Meta: "Coastal"},
		{Title: "Road trip", Meta: "Open road"},
		{Title: "Backpacking", Meta: "Budget"},
		{Title: "Heritage cities", Meta: "Culture"},
	}},
	"football": {Title: "Skills to drill", Items: []Pick{
		{Title: "Dribbling", Meta: "Close control"},
		{Title: "Passing", Meta: "Vision"},
		{Title: "Shooting", Meta: "Finishing"},
		{Title: "Defending", Meta: "Positioning"},
		{Title: "Fitness", Meta: "Stamina"},
	}},
	"community": {Title: "Ways to give back", Items: []Pick{
		{Title: "Volunteering", Meta: "Local NGOs"},
		{Title: "Mentoring", Meta: "Share skills"},
		{Title: "Beach / park cleanups", Meta: "Environment"},
		{Title: "Animal shelters", Meta: "Care"},
		{Title: "Teaching", Meta: "Kids · adults"},
	}},
}
